import type { ViewHelpSpec } from '../types';

export const VIEW_HELP: Record<string, ViewHelpSpec> = {
  'Analyse financière': { purpose:"Comprendre la situation financière de l’établissement à partir des données consolidées dans Vigie.", sources:[{name:'YFDR',format:'CSV'},{name:'EBLC',format:'XLSX'},{name:'YCONSDEP / YCONSREC',format:'XLSX'},'YBALAC','YBALAF',{name:'Compte 5151',format:'CSV'}], notes:["Les pas-à-pas OP@LE seront ajoutés à mesure de leur validation terrain."], indicators:['FDR','BFDR','TRESORERIE_NETTE','JOURS_FDR','CAF_IAF'] },
  'Budget': { purpose:"Suivre la construction et l’exécution budgétaires de l’établissement.", sources:[{name:'Budget OP@LE',format:'.lis ou .xlsx'},{name:'EBLC',format:'XLSX'}], notes:["Le gabarit d’aide est prêt ; le parcours OP@LE reste à documenter."], indicators:['TAUX_EXEC_DEPENSES','TAUX_EXEC_RECETTES'] },
  'Dépenses': { purpose:"Piloter l’exécution des dépenses et identifier les opérations à surveiller.", sources:[{name:'YCONSDEP',format:'XLSX'}], notes:["Le parcours d’export OP@LE reste à documenter."], indicators:['TAUX_EXEC_DEPENSES','CONCENTRATION_FOURNISSEUR'] },
  'Recettes': { purpose:"Piloter l’exécution des recettes et identifier les opérations à surveiller.", sources:[{name:'YCONSREC',format:'XLSX'}], notes:["Le parcours d’export OP@LE reste à documenter."], indicators:['TAUX_EXEC_RECETTES','TNR'] },
  'Trésorerie': { purpose:"Suivre la trajectoire de trésorerie et apprécier sa soutenabilité, sans isoler le seul solde du compte 5151.", sources:[{name:'Écritures du compte 5151',format:'CSV'},'YBALAC','YBALAF',{name:'Analyse financière',format:'FdR / BFdR'}], notes:["Le parcours d’export OP@LE reste à documenter."], indicators:['AUTONOMIE_TRESORERIE','TRESO_APRES_DETTES_EXIGIBLES','TNR','VARIATION_5151_30J','FDR_BFDR'] },
  'Clients': { purpose:"Analyser les créances clients, leur ancienneté et les situations nécessitant une attention particulière.", sources:['YBALAC'], indicators:['STOCK_ANCIEN_CLIENTS','PART_STOCK_ANCIEN','TNR'] },
  'Fournisseurs': { purpose:"Analyser les dettes fournisseurs, leur ancienneté et les situations nécessitant une attention particulière.", sources:['YBALAF'], indicators:['DETTES_EXIGIBLES'] },
  'Comptabilité générale': { purpose:"Examiner les comptes des classes 1 à 8 et les anomalies comptables détectées par Vigie.", sources:[{name:'Données comptables OP@LE — classes 1 à 8',format:'CSV'},'YGPIE1'], notes:["YGPIE1 alimente les pièces non soldées et les rapprochements."], indicators:['SOLDE_COMPTE','PIECES_NON_SOLDEES'] },
  'Maîtrise des risques': { purpose:"Rassembler les signaux financiers et les éléments utiles à la maîtrise des risques.", sources:[{name:'Données des vues métier Vigie',format:'Sources consolidées'}], notes:["Cette vue exploite les données déjà importées dans les autres vues métier."], indicators:['COUVERTURE_PCIF','MAITRISE_PCIF','RISQUES_MAJEURS_PCIF'] },
};
