import { useEffect, useMemo, useState } from 'react';
import { Building2, Database, KeyRound, Plus, RefreshCw, Save, Settings, ShieldCheck, UserRound, UsersRound, X } from 'lucide-react';
import { api } from '../lib/api';
import type { Dashboard } from '../types/dashboard';

type Agency={id:number;name:string;is_active:boolean;establishment_count:number};
type Role={agencyId:number;agencyName:string;role:string};
type User={id:number;email:string;first_name:string;last_name:string;global_role:'ADMIN'|'USER';is_active:boolean;last_login_at?:string;roles:Role[]};
type Registry={id:number;uai:string;name:string;opale_entity?:string|null;is_active:boolean;accounting_agency_id?:number|null};
const roleLabel=(r:string)=>({ACCOUNTANT:'Agent comptable',DEPUTY:'Fondé de pouvoir',AGENCY_USER:'Agent agence',VIEWER:'Lecteur'}[r]||r);
export function AdminView({dash,reload}:{dash:Dashboard;reload:()=>Promise<void>}){
 const[tab,setTab]=useState<'overview'|'users'|'establishments'|'agencies'|'sources'>('overview');
 const[users,setUsers]=useState<User[]>([]),[agencies,setAgencies]=useState<Agency[]>([]),[ets,setEts]=useState<Registry[]>([]),[modal,setModal]=useState<any>(null),[error,setError]=useState('');
 const refresh=async()=>{const[u,a,e]=await Promise.all([api.adminUsers(),api.adminAgencies(),api.establishments()]);setUsers(u.users||[]);setAgencies(a.agencies||[]);setEts(e.establishments||[])};
 useEffect(()=>{void refresh()},[]);
 const sourceRows=useMemo(()=>dash.establishments.map(e=>({name:e.name,uai:e.uai,sources:e.sources,stale:e.staleSources||[]})),[dash]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError('');const f=new FormData(e.currentTarget);try{
   if(modal?.kind==='user'){const body={email:f.get('email'),firstName:f.get('firstName'),lastName:f.get('lastName'),globalRole:f.get('globalRole'),password:f.get('password')};const r=await api.createUser(body);const aid=Number(f.get('agencyId'));if(aid)await api.updateUserAgencies(r.user.id,[{agencyId:aid,role:String(f.get('role')||'VIEWER')}]);}
   if(modal?.kind==='agency')await api.createAgency(String(f.get('name')||''));
   if(modal?.kind==='reset')await api.resetUserPassword(modal.user.id,String(f.get('password')||''));
   setModal(null);await refresh();await reload();
 }catch(x){setError(x instanceof Error?x.message:'Erreur') }}
 async function toggleUser(u:User){await api.updateUser(u.id,{firstName:u.first_name,lastName:u.last_name,globalRole:u.global_role,isActive:!u.is_active});await refresh()}
 async function setAgency(registryId:number,agencyId:number|null){await api.setEstablishmentAgency(registryId,agencyId);await refresh();await reload()}
 return <div className="page admin-page"><div className="pagehead"><div><h2>Administration</h2><p>Administration locale de Vigie. Le référentiel est préparé pour sa future centralisation dans EPLE Core.</p></div><button className="btn-soft" onClick={()=>void refresh()}><RefreshCw size={15}/> Actualiser</button></div>
 <div className="admin-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}><Settings size={16}/> Vue d’ensemble</button><button className={tab==='users'?'active':''} onClick={()=>setTab('users')}><UsersRound size={16}/> Utilisateurs</button><button className={tab==='establishments'?'active':''} onClick={()=>setTab('establishments')}><Building2 size={16}/> Établissements</button><button className={tab==='agencies'?'active':''} onClick={()=>setTab('agencies')}><ShieldCheck size={16}/> Agences</button><button className={tab==='sources'?'active':''} onClick={()=>setTab('sources')}><Database size={16}/> Sources</button></div>
 {tab==='overview'&&<><div className="admin-kpis"><div><UsersRound/><b>{users.filter(x=>x.is_active).length}</b><span>utilisateurs actifs</span></div><div><Building2/><b>{ets.filter(x=>x.is_active).length}</b><span>établissements actifs</span></div><div><ShieldCheck/><b>{agencies.filter(x=>x.is_active).length}</b><span>agences comptables</span></div><div><Database/><b>{sourceRows.reduce((n,e)=>n+e.stale.length,0)}</b><span>sources à actualiser</span></div></div><section className="admin-panel"><h3>Socle commun EPLE Tools</h3><p>Vigie conserve pour l’instant son administration locale. Les identités, établissements, agences et rattachements sont isolés comme référentiels afin de pouvoir être remplacés ensuite par EPLE Core sans déplacer les données métier de Vigie.</p></section></>}
 {tab==='users'&&<section className="admin-panel"><div className="admin-panel-head"><div><h3>Utilisateurs</h3><p>Accès à Vigie et périmètre d’agence.</p></div><button className="btn-primary-v" onClick={()=>setModal({kind:'user'})}><Plus size={15}/> Utilisateur</button></div><div className="admin-table">{users.map(u=><div className="admin-row" key={u.id}><UserRound/><div className="admin-main"><b>{[u.first_name,u.last_name].filter(Boolean).join(' ')||u.email}</b><small>{u.email} · {u.global_role==='ADMIN'?'Administrateur':(u.roles.map(r=>`${roleLabel(r.role)} · ${r.agencyName}`).join(', ')||'Aucun périmètre')}</small></div><span className={`admin-state ${u.is_active?'ok':'off'}`}>{u.is_active?'Actif':'Suspendu'}</span><button className="btn-soft" onClick={()=>setModal({kind:'reset',user:u})}><KeyRound size={14}/> Mot de passe</button><button className="btn-soft" onClick={()=>void toggleUser(u)}>{u.is_active?'Suspendre':'Réactiver'}</button></div>)}</div></section>}
 {tab==='establishments'&&<section className="admin-panel"><div className="admin-panel-head"><div><h3>Établissements</h3><p>Rattachement au référentiel des agences comptables.</p></div></div><div className="admin-table">{ets.map(e=><div className="admin-row" key={e.id}><Building2/><div className="admin-main"><b>{e.name}</b><small>{e.uai} · {e.opale_entity||'ETS Op@le non renseigné'}</small></div><select value={e.accounting_agency_id||''} onChange={x=>void setAgency(e.id,x.target.value?Number(x.target.value):null)}><option value="">Sans agence</option>{agencies.filter(a=>a.is_active).map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select></div>)}</div></section>}
 {tab==='agencies'&&<section className="admin-panel"><div className="admin-panel-head"><div><h3>Agences comptables</h3><p>Périmètres comptables utilisés pour filtrer les données accessibles.</p></div><button className="btn-primary-v" onClick={()=>setModal({kind:'agency'})}><Plus size={15}/> Agence</button></div><div className="admin-table">{agencies.map(a=><div className="admin-row" key={a.id}><ShieldCheck/><div className="admin-main"><b>{a.name}</b><small>{a.establishment_count} établissement{a.establishment_count>1?'s':''} rattaché{a.establishment_count>1?'s':''}</small></div><span className={`admin-state ${a.is_active?'ok':'off'}`}>{a.is_active?'Active':'Inactive'}</span></div>)}</div></section>}
 {tab==='sources'&&<section className="admin-panel"><div className="admin-panel-head"><div><h3>Sources Vigie</h3><p>Disponibilité et fraîcheur des données par établissement.</p></div></div><div className="source-matrix"><div className="source-head"><b>Établissement</b>{['balance','budget','purchases','fdr','treasury','financial'].map(s=><b key={s}>{s==='purchases'?'Achats':s==='financial'?'Analyse':s}</b>)}</div>{sourceRows.map(e=><div className="source-line" key={e.uai||e.name}><span><b>{e.name}</b><small>{e.uai}</small></span>{['balance','budget','purchases','fdr','treasury','financial'].map(s=>{const v=(e.sources as any)?.[s];return <span key={s} className={`source-dot ${!v?'missing':e.stale.includes(s)?'stale':'fresh'}`} title={!v?'Source absente':e.stale.includes(s)?'À actualiser':'Disponible'}>{v?'●':'—'}</span>})}</div>)}</div></section>}
 {modal&&<div className="modalveil" onClick={()=>setModal(null)}><div className="importbox" onClick={e=>e.stopPropagation()}><button className="x" onClick={()=>setModal(null)}><X/></button><h3>{modal.kind==='user'?'Créer un utilisateur':modal.kind==='agency'?'Créer une agence':'Réinitialiser le mot de passe'}</h3><form onSubmit={submit}>{modal.kind==='user'&&<><label>Prénom</label><input name="firstName"/><label>Nom</label><input name="lastName"/><label>Adresse électronique</label><input name="email" type="email" required/><label>Profil global</label><select name="globalRole"><option value="USER">Utilisateur</option><option value="ADMIN">Administrateur</option></select><label>Agence</label><select name="agencyId"><option value="">Aucune</option>{agencies.filter(a=>a.is_active).map(a=><option value={a.id} key={a.id}>{a.name}</option>)}</select><label>Rôle dans l’agence</label><select name="role"><option value="ACCOUNTANT">Agent comptable</option><option value="DEPUTY">Fondé de pouvoir</option><option value="AGENCY_USER">Agent agence</option><option value="VIEWER">Lecteur</option></select></>}{modal.kind==='agency'&&<><label>Nom de l’agence</label><input name="name" required autoFocus/></>}{(modal.kind==='user'||modal.kind==='reset')&&<><label>{modal.kind==='user'?'Mot de passe initial':'Nouveau mot de passe'}</label><input name="password" type="password" minLength={12} required/><small>12 caractères minimum.</small></>}{error&&<div className="result">{error}</div>}<button className="btn-primary-v"><Save size={15}/> Enregistrer</button></form></div></div>}
 </div>
}
