import type { HelpIndicator } from '../types';

/**
 * Référentiel métier central des indicateurs Vigie.
 *
 * Une définition n'est déclarée qu'ici puis référencée par son identifiant
 * depuis les aides de vues. Les calculs applicatifs restent, à ce stade,
 * dans leurs modules métier : ce référentiel documente leur sens et leur
 * méthode sans modifier leur implémentation.
 */
export const INDICATOR_REGISTRY = {
  FDR:{name:'Fonds de roulement',short:'FdR',meaning:'Ressources durables restant disponibles après financement des emplois durables.',formula:{expression:'Ressources stables − emplois stables'},reading:'Un FdR positif constitue une marge structurelle ; son interprétation doit être rapprochée du BFdR et des besoins connus.'},
  BFDR:{name:'Besoin en fonds de roulement',short:'BFdR',meaning:'Besoin ou ressource généré par le décalage entre créances et dettes d’exploitation.',formula:{expression:'Actif circulant d’exploitation − passif circulant d’exploitation'},reading:'Un BFdR positif consomme de la trésorerie ; un BFdR négatif constitue une ressource de cycle.'},
  TRESORERIE_NETTE:{name:'Trésorerie nette',meaning:'Résulte de l’équilibre entre le FdR et le BFdR.',formula:{expression:'FdR − BFdR'},caution:'Dans Vigie, le solde observé du 5151 est affiché séparément : il ne doit pas être confondu automatiquement avec la trésorerie nette comptable.'},
  JOURS_FDR:{name:'Jours de FdR',meaning:'Exprime le FdR en nombre de jours de charges décaissables.',formula:{numerator:'FdR',denominator:'charges décaissables de fonctionnement',suffix:'× 360'},reading:'Permet de comparer des établissements de tailles différentes.'},
  CAF_IAF:{name:'Capacité / insuffisance d’autofinancement',short:'CAF / IAF',meaning:'Ressource interne dégagée par l’activité, ou insuffisance lorsque le solde est négatif.',formula:{expression:'Produits encaissables − charges décaissables'},caution:'Vigie applique la reconstruction définie par ses données comptables disponibles ; toujours lire la provenance et l’exercice.'},
  TAUX_EXEC_DEPENSES:{name:'Taux d’exécution des dépenses',meaning:'Part des crédits ouverts déjà consommée.',formula:{numerator:'dépenses réalisées',denominator:'crédits ouverts',suffix:'× 100'},reading:'À rapprocher du calendrier, des engagements et des dépenses restant à réaliser.',caution:'Ce taux n’est pas une cible normative : il dépend du calendrier réel des opérations.'},
  TAUX_EXEC_RECETTES:{name:'Taux d’exécution des recettes',meaning:'Part des prévisions de recettes déjà réalisée.',formula:{numerator:'recettes réalisées',denominator:'prévisions de recettes',suffix:'× 100'},reading:'À interpréter selon le calendrier réel des encaissements et des droits constatés.',caution:'Une exécution faible peut être normale si les recettes sont saisonnières ou attendues en fin d’exercice.'},
  CONCENTRATION_FOURNISSEUR:{name:'Concentration fournisseur',meaning:'Part de l’encours analysé portée par le premier fournisseur.',formula:{numerator:'montant du 1er fournisseur',denominator:'montant total analysé',suffix:'× 100'},reading:'Une forte concentration est un signal d’examen, pas une anomalie en elle-même.'},
  TNR:{name:'Taux de non-recouvrement',short:'TnR',meaning:'Rapporte les créances clients restant à recouvrer au volume de ventes de produits et prestations.',formula:{numerator:'soldes débiteurs des comptes 411 à 418',denominator:'recettes nettes du compte 70',suffix:'× 100'},reading:'Plus le TnR est élevé, plus le poids des créances non recouvrées est important au regard de l’activité ; il peut signaler une pression future sur la trésorerie.',caution:'Indicateur de compte financier : ne pas le confondre avec 100 % moins un taux d’encaissement calculé sur une autre assiette.',source:'M9.6 / indicateurs du compte financier'},
  AUTONOMIE_TRESORERIE:{name:'Autonomie de trésorerie observée',meaning:'Nombre de jours de charges nettes de fonctionnement couverts par le solde observé du compte 5151.',formula:{numerator:'solde du compte 5151',denominator:'charges nettes de fonctionnement',suffix:'× 360'},reading:'Lecture Vigie : < 30 j = alerte ; 30–42 j = prudence ; 42–65 j = confortable ; > 65 j = autonomie élevée à apprécier.',caution:'Les seuils sont des repères de pilotage Vigie, non des seuils réglementaires.'},
  TRESO_APRES_DETTES_EXIGIBLES:{name:'Après dettes exigibles',meaning:'Simulation de la liquidité restant disponible après décaissement des dettes échues identifiées dans YBALAF.',formula:{expression:'solde 5151 − dettes exigibles identifiées'},caution:'Indicateur de pilotage : ce n’est pas une grandeur comptable réglementaire et sa qualité dépend de l’exhaustivité de YBALAF.'},
  VARIATION_5151_30J:{name:'Variation à 30 jours',short:'Δ 30 j',meaning:'Évolution du solde 5151 entre la dernière période disponible et la période de comparaison à 30 jours.',formula:{numerator:'5151 actuel − 5151 à J−30',denominator:'5151 à J−30',suffix:'× 100'},caution:'Le calcul dépend des périodes effectivement disponibles ; Vigie ne simule pas une donnée absente.'},
  FDR_BFDR:{name:'FdR / BFdR',meaning:'Le FdR décrit la marge structurelle et le BFdR le besoin ou la ressource du cycle d’exploitation.',formula:{expression:'trésorerie nette = FdR − BFdR'},caution:'Comparer des données de même date. Le 5151 courant et les données du dernier COFI peuvent relever de dates différentes.'},
  STOCK_ANCIEN_CLIENTS:{name:'Stock ancien',meaning:'Montant des créances classées dans la tranche d’ancienneté la plus élevée disponible dans YBALAC.',formula:{expression:'somme des créances > 121 jours'},caution:'> 121 jours ne signifie pas > 1 an.'},
  PART_STOCK_ANCIEN:{name:'Part du stock ancien',meaning:'Poids des créances anciennes dans l’encours analysé.',formula:{numerator:'créances > 121 jours',denominator:'encours total YBALAC',suffix:'× 100'},reading:'Une part élevée oriente le contrôle vers les débiteurs et les actions de recouvrement.'},
  DETTES_EXIGIBLES:{name:'Dettes exigibles',meaning:'Montants fournisseurs arrivés à échéance et encore présents dans la balance âgée.',formula:{expression:'somme des dettes échues identifiées dans YBALAF'},reading:'Elles peuvent expliquer qu’un solde 5151 paraisse temporairement élevé avant décaissement.',caution:'Le montant dépend de la qualité et de la date de l’export YBALAF.'},
  SOLDE_COMPTE:{name:'Solde d’un compte',meaning:'Différence entre les mouvements débiteurs et créditeurs du compte.',formula:{expression:'total débit − total crédit'},caution:'Le sens économique du signe dépend de la nature du compte.'},
  PIECES_NON_SOLDEES:{name:'Pièces non soldées',meaning:'Pièces encore ouvertes dans YGPIE1 à la date de l’export.',formula:{expression:'nombre et montant des pièces dont le solde n’est pas nul'},reading:'L’ancienneté et le compte expliquent la priorité de contrôle ; une pièce ouverte n’est pas automatiquement une anomalie.'},
  COUVERTURE_PCIF:{name:'Couverture du diagnostic',meaning:'Part du référentiel PCIF effectivement renseignée.',formula:{numerator:'questions renseignées',denominator:'questions applicables du diagnostic',suffix:'× 100'},reading:'Toujours lire le niveau de maîtrise avec la couverture : une maîtrise élevée sur une faible couverture est peu représentative.'},
  MAITRISE_PCIF:{name:'Niveau de maîtrise',meaning:'Indicateur issu de PCIF Académie pour le périmètre renseigné.',caution:'Vigie restitue cet indicateur et le contextualise ; il ne remplace pas le diagnostic PCIF.'},
  RISQUES_MAJEURS_PCIF:{name:'Risques majeurs',meaning:'Risques PCIF dont le niveau atteint le seuil majeur retenu par la démarche.',formula:{expression:'gravité × probabilité ≥ 6 / 9'},reading:'Ils orientent l’accompagnement et le plan d’action ; Vigie n’en modifie pas la cotation.'}
} as const satisfies Record<string, HelpIndicator>;

export type IndicatorId = keyof typeof INDICATOR_REGISTRY;

export function getIndicator(id: IndicatorId): HelpIndicator {
  return INDICATOR_REGISTRY[id];
}
